### ISSUE TITLE
Current Container and source has issues

### ISSUE THREAD

**Issue by blairjj** [NVIDIA/ngc-container-replicator#28]
Howdy,

After the latest merge, there seems to be an issue running the container (as well as downloading and building locally):

> [ngc@hpctest-ngc ~]$ docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/output \
>     deepops/replicator --project=nvidia --min-version=17.12 \
>                        --image=tensorflow --image=pytorch --image=tensorrt \
>                        --dry-run \
>                        --api-key=<my key goes here>
Unable to find image 'deepops/replicator:latest' locally
latest: Pulling from deepops/replicator
33847f680f63: Pull complete
e8124950597e: Pull complete
cfdfe715e2ab: Pull complete
11063ba8ad10: Pull complete
9cca960c0455: Pull complete
59c710625a0b: Pull complete
43c7bdc918aa: Pull complete
719fe337f921: Pull complete
e76245b707c9: Pull complete
1788f284abad: Pull complete
0edde909c898: Pull complete
5ebd9e0bdab6: Pull complete
0da1f63a5b3b: Pull complete
205b32bbfc59: Pull complete
0de6974af104: Pull complete
afe609d6ba8e: Pull complete
5ad296e03acc: Pull complete
1107645e1064: Pull complete
df77e4a2892d: Pull complete
79c69c4aa875: Pull complete
714ec4dbe631: Pull complete
232daeae6c76: Pull complete
e02dcc83a9f8: Pull complete
b89af75cf6e0: Pull complete
d329b23c4357: Pull complete
7803980f99c7: Pull complete
2a229df2f624: Pull complete
b185763ce13b: Pull complete
Digest: sha256:f1a71af92e6332f9b2be718cc309103d9fe359fb1d0aec04f4924e5030c283b8
Status: Downloaded newer image for deepops/replicator:latest
2021-08-24 19:02:11,356 - ngc_replicator.ngc_replicator - 30 - INFO - Initializing Replicator
2021-08-24 19:02:12,495 - nvidia_deepops.docker.registry.ngcregistry - 126 - INFO - GET https://api.ngc.nvidia.com/v2/orgs - took 0.6229122190270573 sec
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded
/usr/local/lib/python3.6/site-packages/ngc_replicator-0.4.0-py3.6.egg/ngc_replicator/ngc_replicator.py:57: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  tmp = yaml.load(file)
Traceback (most recent call last):

**Comment by ajdecon** [comment]
Investigating, and looks like this would have been caused by merging #22 to upgrade PyYAML. This pulled in a PyYAML CVE fix that breaks our process for loading external config files: https://github.com/yaml/pyyaml/issues/420

**Comment by ajdecon** [comment]
@blairjj : This should be fixed by #29 which is now merged, please feel free to test

**Comment by blairjj** [comment]
YAY!  Works...
